sudo: true
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:lyx-devel/release
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-5
  - sudo apt-get install -qq graphviz
  - sudo apt-get install -qq babel
  - sudo apt-get install -qq lyx
  - sudo apt-get install -qq texlive # For pdflatex
  - sudo apt-get install -qq texlive-* # For pdflatex
  #- sudo apt-get install -qq texlive-full # For pdflatex
  #- sudo apt-get install -qq texlive-latex-base # For pdflatex
  - sudo apt-get source -qq pgf # TikZ
  - sudo apt-get install -qq pgf # TikZ
  - sudo pip install codecov
  - ./install_oclint.sh

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libboost1.55-all-dev

script:
  - type dot
  - ./build_test_debug.sh
  - ./boost_graph_tutorial_test
  - ./get_code_cov.sh
  - codecov
  - travis_wait 30 ./do_oclint.sh
  #- ./clean.sh
  #- ./build_exe_release.sh
  # - ./build_pdf.sh

after_success: 
  - ls
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - ls
  - pdflatex -v
  - cd ~; find . | egrep "\.tex"
  - cd ~; find . | egrep "\.log"
  - cd /usr; find . | egrep "/texlive$"
  - cd /opt; find . | egrep "/texlive$"
  - cd /; find . | egrep "/texlive$"
  #- which tlmgr
  - echo $PATH
  - cat /home/travis/build/richelbilderbeek/BoostGraphTutorial/BoostGraphTutorial/boost_graph_tutorial.tex
